import { LayerSpecification } from '../Types';

const layers: LayerSpecification[] = [
  {
    id: 'buildings-background',
    type: 'fill',
    source: 'indoor',
    filter: ['any', ['has', 'building'], ['has', 'building:part']],
    style: {
      fillColor: '#E6E4E0',
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 16.5, 0, 18, 1],
    },
  },
  {
    id: 'level-background',
    type: 'fill',
    source: 'indoor',
    filter: ['filter-==', 'indoor', 'level'],
    style: {
      fillColor: '#E6E4E0',
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 16.5, 0, 18, 1],
    },
  },
  {
    id: 'indoor-gardens',
    type: 'fill',
    source: 'indoor',
    filter: ['filter-==', 'leisure', 'garden'],
    style: {
      visibility: 'visible',
      fillColor: '#cde8a2',
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'indoor-parkings',
    type: 'fill',
    source: 'indoor',
    filter: ['filter-==', 'amenity', 'parking'],
    style: {
      fillColor: '#D7CCC8',
      fillOutlineColor: '#000000',
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'indoor-parkings-patterns',
    type: 'fill',
    source: 'indoor',
    filter: ['filter-==', 'amenity', 'parking'],
    style: {
      // "fill-pattern-DEPRECATED": "si-main-3",
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 0.1],
      fillTranslateAnchor: 'viewport',
    },
  },
  {
    id: 'indoor-corridors',
    type: 'fill',
    source: 'indoor',
    filter: ['filter-==', 'indoor', 'corridor'],
    style: {
      fillColor: '#D7CCC8',
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'indoor-rooms',
    type: 'fill',
    source: 'indoor',
    filter: [
      'any',
      ['in', ['get', 'indoor'], ['literal', ['room', 'area']]],
      ['filter-==', 'railway', 'platform'],
    ],
    style: {
      fillColor: '#A1887F',
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'indoor-rooms-borders',
    type: 'line',
    source: 'indoor',
    filter: ['any', ['filter-==', 'indoor', 'room']],
    style: {
      lineColor: '#000',
      lineWidth: 1,
      lineOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'indoor-areas',
    type: 'fill',
    source: 'indoor',
    filter: ['filter-==', 'indoor', 'area'],
    style: {
      fillColor: '#D7CCC8',
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'indoor-highways-area',
    type: 'fill',
    source: 'indoor',
    filter: ['all', ['filter-==', 'highway', 'pedestrian'], ['has', 'level']],
    style: {
      fillColor: [
        'interpolate',
        ['linear'],
        ['zoom'],
        16,
        'hsl(230, 16%, 94%)',
        16.25,
        'hsl(230, 50%, 98%)',
      ],
      fillOutlineColor: 'hsl(230, 26%, 88%)',
      fillOpacity: 1,
    },
  },
  {
    id: 'indoor-highways-area-pattern',
    type: 'fill',
    source: 'indoor',
    filter: ['all', ['filter-==', 'highway', 'pedestrian'], ['has', 'level']],
    style: {
      // "fill-pattern-DEPRECATED": "pedestrian-polygon",
      fillColor: 'hsl(0, 0%, 100%)',
      fillOutlineColor: 'hsl(35, 10%, 83%)',
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'indoor-balcony',
    type: 'fill',
    source: 'indoor',
    filter: ['all', ['filter-==', 'indoor', 'area'], ['filter-==', 'balcony', 'yes']],
    style: {
      fillColor: '#BDBDBD',
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'indoor-stairs',
    type: 'fill',
    source: 'indoor',
    filter: [
      'any',
      ['filter-==', 'stairs', 'yes'],
      ['filter-==', 'elevator', 'yes'],
      ['filter-==', 'highway', 'elevator'],
    ],
    style: {
      fillColor: '#7B635A',
      fillOutlineColor: '#000000',
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'indoor-walls',
    type: 'line',
    source: 'indoor',
    filter: ['filter-==', 'indoor', 'wall'],
    style: {
      lineColor: '#000000',
      lineOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'indoor-barriers',
    type: 'line',
    source: 'indoor',
    filter: ['has', 'barrier'],
    style: {
      lineColor: '#000000',
      lineOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'indoor-blocks',
    type: 'fill',
    source: 'indoor',
    filter: ['filter-==', 'indoor', 'block'],
    style: {
      fillColor: '#000000',
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'indoor-handrail',
    type: 'line',
    source: 'indoor',
    filter: ['filter-==', 'handrail', 'yes'],
    style: {
      lineColor: '#000000',
      lineOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 19, 1],
    },
  },
  {
    id: 'indoor-rails',
    type: 'line',
    source: 'indoor',
    filter: ['filter-==', 'railway', 'rail'],
    style: {
      lineColor: 'hsl(230, 10%, 74%)',
      lineOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 19, 1],
    },
  },
  {
    id: 'indoor-rails-tracks',
    type: 'line',
    source: 'indoor',
    filter: ['filter-==', 'railway', 'rail'],
    style: {
      lineColor: 'hsl(230, 10%, 74%)',
      lineOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 19, 1],
      lineWidth: ['interpolate', ['exponential', 1.5], ['zoom'], 14, 4, 20, 8],
      lineDasharray: [0.1, 15],
    },
  },
  {
    id: 'indoor-furniture',
    type: 'fill',
    source: 'indoor',
    filter: [
      'any',
      [
        'in',
        ['get', 'indoor'],
        [
          'literal',
          ['table', 'cupboard', 'chair', 'kitchen', 'sofa', 'tv', 'shelf', 'furniture-item'],
        ],
      ],
      ['filter-==', 'trashcan', 'yes'],
      ['filter-==', 'copier', 'yes'],
      ['filter-==', 'amenity', 'vending_machine'],
    ],
    style: {
      fillColor: '#000',
      fillOutlineColor: '#000',
      fillOpacity: ['interpolate', ['linear'], ['zoom'], 18, 0, 19, 0.2],
    },
  },
  {
    id: 'indoor-steps',
    type: 'line',
    source: 'indoor',
    filter: ['all', ['filter-==', 'highway', 'steps'], ['!', ['has', 'conveying']]],
    style: {
      lineWidth: ['interpolate', ['exponential', 1.5], ['zoom'], 17, 1, 18, 1.6, 19, 6],
      lineColor: 'hsl(0, 0%, 100%)',
      lineDasharray: [
        'step',
        ['zoom'],
        [1, 0],
        17,
        [1, 0],
        17.5,
        [1.75, 1],
        18,
        [1, 0.75],
        19,
        [0.3, 0.3],
      ],
      lineOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 17.25, 1],
      lineJoin: 'round',
    },
  },
  {
    id: 'indoor-conveying',
    type: 'line',
    source: 'indoor',
    filter: ['all', ['filter-==', 'highway', 'steps'], ['has', 'conveying']],
    style: {
      lineWidth: ['interpolate', ['exponential', 1.5], ['zoom'], 17, 1, 18, 1.6, 19, 6],
      lineColor: '#FF0000',
      lineDasharray: [
        'step',
        ['zoom'],
        [1, 0],
        17,
        [1, 0],
        17.5,
        [1.75, 1],
        18,
        [1, 0.75],
        19,
        [0.3, 0.3],
      ],
      lineOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 17.25, 1],
      lineJoin: 'round',
    },
  },
  {
    // interactive: true,
    // minzoom: 17,
    id: 'poi-indoor-text-ref',
    type: 'symbol',
    source: 'indoor',
    filter: ['filter-==', 'indoor', 'room'],
    style: {
      textLineHeight: 1.2,
      textSize: ['interpolate', ['linear'], ['zoom'], 17, 10, 20, 12],
      textAllowOverlap: false,
      textIgnorePlacement: false,
      textMaxAngle: 38,
      textFont: ['DIN Offc Pro Medium', 'Arial Unicode MS Regular'],
      symbolPlacement: 'point',
      textPadding: 2,
      visibility: 'visible',
      textRotationAlignment: 'viewport',
      textAnchor: 'center',
      textField: '{ref}', // Used to be '{name}'
      textLetterSpacing: 0.02,
      textMaxWidth: 8,
      textColor: '#65513d',
      textHaloColor: '#ffffff',
      textHaloWidth: 1,
      textOpacity: ['interpolate', ['linear'], ['zoom'], 18, 0, 18.5, 0.5, 19, 1],
    },
  },
  {
    // interactive: true,
    // minzoom: 17,
    id: 'poi-indoor',
    source: 'indoor',
    filter: ['boolean', false],
    type: 'symbol',
    style: {
      textLineHeight: 1.2,
      iconSize: ['interpolate', ['linear'], ['zoom'], 17, 0.5, 20, 1],
      textSize: ['interpolate', ['linear'], ['zoom'], 17, 11, 20, 13],
      textAllowOverlap: false,
      iconImage: '{maki}-15',
      iconAnchor: 'center',
      textIgnorePlacement: false,
      textMaxAngle: 38,
      symbolSpacing: 250,
      textFont: ['DIN Offc Pro Medium', 'Arial Unicode MS Regular'],
      symbolPlacement: 'point',
      textPadding: 2,
      visibility: 'visible',
      textOffset: [0, 1],
      iconOptional: false,
      textRotationAlignment: 'viewport',
      textAnchor: 'top',
      textField: '{name}',
      textLetterSpacing: 0.02,
      textMaxWidth: 8,
      iconAllowOverlap: true,
      textColor: '#65513d',
      textHaloColor: '#ffffff',
      textHaloWidth: 1,
      textOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 17.5, 0.5, 19, 1],
      iconOpacity: ['interpolate', ['linear'], ['zoom'], 17, 0, 17.5, 0.5, 19, 1],
    },
  },
];

export default layers;
