name: E2E Testing

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  e2e-test:
    strategy:
      matrix:
        platform: [android, ios]
        include:
          - platform: ios
            os: macos-latest
          - platform: android
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Install idb & Dependencies
        if: matrix.platform == 'ios'
        run: |
          brew tap facebook/fb
          brew install idb-companion ffmpeg
          brew install --cask android-platform-tools

      - name: Setup Ruby & Cocoapods
        if: matrix.platform == 'ios'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Setup Android
        if: matrix.platform == 'android'
        uses: android-actions/setup-android@v3

      - name: Setup Android Emulator
        if: matrix.platform == 'android'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: echo "Emulator started"

      - name: Setup iOS Simulator
        if: matrix.platform == 'ios'
        run: |
          xcrun simctl list
          UDID=$(xcrun simctl create "iPhone 15" com.apple.CoreSimulator.SimDeviceType.iPhone-15 com.apple.CoreSimulator.SimRuntime.iOS-17-4)
          xcrun simctl boot "$UDID"

      - name: Prebuild & Run App
        working-directory: ./client
        run: |
          npx expo prebuild
          if [ "${{ matrix.platform }}" = "ios" ]; then
            cd ios && pod install && cd ..
            npm run ios
          else
            npm run android
          fi

      - name: Run Maestro Tests
        working-directory: .
        run: |
          sleep 10
          if [ "${{ matrix.platform }}" = "ios" ]; then
            idb_companion --udid $UDID &
            sleep 5
          fi
          if [ ! -f "maestro/flows/app.yml" ]; then
            echo "Test file not found"
            exit 1
          fi
          maestro test maestro/flows/app.yml

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-${{ matrix.platform }}
          path: ~/.maestro/logs/
