name: iOS E2E Testing

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  ios-e2e:
    name: Run iOS E2E tests
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Environment variables
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: echo "EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN=${{ secrets.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN }}" > .env

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Install iOS dependencies
        run: |
          brew tap facebook/fb
          brew install facebook/fb/idb-companion

      - name: Install iOS pods
        run: |
          cd ios
          pod install
          cd ..

      - name: Start iOS app
        run: npm run ios

      - name: Run E2E tests
        run: maestro test .maestro/app.yml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-e2e-results
          path: |
            ~/.maestro/logs/
            ~/.maestro/videos/
