name: Maestro E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  e2e-tests:
    name: Maestro E2E Tests
    runs-on: macos-latest
    env:
      EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN }}
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Setup Expo
        uses: expo/expo-github-action@v8

      - name: Prebuild iOS
        run: |
          npx expo prebuild
          npm run ios

      - name: Run Maestro Tests
        uses: dniHze/maestro-test-action@v1
        with:
          flow: client/maestro/flows
          report: client/test-reports/report.xml
          screenshot-dir: client/.maestro/screenshots

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            client/test-reports/
            client/.maestro/screenshots/
          retention-days: 14

      - name: Post Test Results to PR
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: E2E Test Results
          path: client/test-reports/report.xml
          reporter: jest-junit
          fail-on-error: true
