name: iOS E2E Testing

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  ios-e2e:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json

      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ./client/ios/build
          key: ${{ runner.os }}-ios-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-ios-build-

      - uses: actions/cache@v3
        with:
          path: ./client/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install dependencies
        working-directory: ./client
        run: |
          npm ci
          npx expo install

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Install iOS dependencies
        run: |
          brew install watchman
          brew tap facebook/fb
          brew install idb-companion

      - name: Setup iOS Simulator
        run: |
          xcrun simctl list
          UDID=$(xcrun simctl create "iPhone 15" "com.apple.CoreSimulator.SimDeviceType.iPhone-15" "com.apple.CoreSimulator.SimRuntime.iOS-17-4")
          xcrun simctl boot "$UDID"

          echo "Waiting for simulator to boot..."
          until xcrun simctl list devices | grep -q "$UDID.*Booted"; do
            sleep 2
          done
          echo "Simulator booted successfully"

      - name: Prebuild and Build iOS App
        working-directory: ./client
        env:
          EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN }}
        run: |
          echo "Running expo prebuild..."
          npx expo prebuild --platform ios --clean

          echo "Installing pods..."
          cd ios && pod install && cd ..

          echo "Building the app..."
          xcodebuild -workspace ios/*.xcworkspace \
            -scheme client \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            clean build

      - name: Install App on Simulator
        run: |
          echo "Installing the app..."
          xcrun simctl install booted ./client/ios/build/Build/Products/Debug-iphonesimulator/client.app
          echo "Verifying installed apps..."
          xcrun simctl listapps booted | grep "com.anonymous.client" || echo "App installation failed"

      - name: Start App Manually
        run: |
          echo "Manually launching the app..."
          xcrun simctl launch booted com.anonymous.client || echo "App launch failed"

      - name: Run Maestro Tests
        working-directory: ./client
        run: |
          echo "Running Maestro tests..."
          maestro test maestro/app.yml --debug-output ./maestro-logs

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-ios
          path: |
            ~/.maestro/logs/
            ~/.maestro/videos/
            ./maestro-logs/
