name: iOS E2E Testing

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  ios-e2e:
    name: Run iOS E2E tests
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Install iOS dependencies
        run: |
          brew install watchman
          brew tap facebook/fb
          brew install idb-companion

      - name: Setup iOS Simulator
        run: |
          UDID=$(xcrun simctl create "iPhone 15" "com.apple.CoreSimulator.SimDeviceType.iPhone-15" "com.apple.CoreSimulator.SimRuntime.iOS-17-4")
          xcrun simctl boot "$UDID"
          until xcrun simctl list devices | grep -q "$UDID.*Booted"; do
            sleep 2
          done

      - name: Build iOS app
        env:
          EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN }}
        run: |
          npx expo prebuild --platform ios --clean
          cd ios && pod install && cd ..
          xcodebuild -workspace ios/*.xcworkspace \
            -scheme client \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            clean build

      - name: Install and launch app
        run: |
          xcrun simctl install booted ./client/ios/build/Build/Products/Debug-iphonesimulator/client.app
          xcrun simctl launch booted com.anonymous.client

      - name: Run E2E tests
        run: maestro test maestro/app.yml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-e2e-results
          path: |
            ~/.maestro/logs/
            ~/.maestro/videos/
