name: Maestro E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - 'maestro/**'
      - 'package.json'
      - 'app.json'
      - 'package-lock.json'

jobs:
  e2e-tests:
    name: Maestro E2E Tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest

      - name: Prebuild iOS
        run: |
          npx expo prebuild
          npm run ios

      # Here's the marketplace action
      - name: Run Maestro Tests
        uses: dniHze/maestro-test-action@v1
        with:
          flow: maestro/flows
          report: test-reports/report.xml
          screenshot-dir: .maestro/screenshots
          env: |
            APP_ENV=testing
            EXPO_USE_CUSTOM_PORTS=true

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            test-reports/
            .maestro/screenshots/
          retention-days: 14

      - name: Post Test Results to PR
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: E2E Test Results
          path: test-reports/report.xml
          reporter: jest-junit
          fail-on-error: true
